version: '3.2'

services:
  mssqldev:
    build: .
    image: mcmoe/mssqldocker:v2017.CU12.1
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: 2astazeY
      MSSQL_DB: dev
      MSSQL_USER: Kobeissi
      MSSQL_PASSWORD: 7ellowEl7akey
    ports:
      - "1433:1433"
    container_name: mssqldev
